export const COURSE_DATA = {
  levels: [
    {
      level: 1,
      name: "Beginner Speaking",
      weeks: [
        {
          week: 1,
          title: "Greetings and Basic Replies",
          days: [
            {
              day: 1,
              title: "Simple Greeting",
              word: "greeting",
              meaning: "Basic hello conversation",
              example: "Hello sir. I am fine.",
              vocabulary: ["hello", "hi", "good", "morning"],
              supportWords: ["hello", "hi", "good", "morning"],
              speakingFocus: "Basic greeting conversation",
              practicePrompt: "Say hello and tell how you are today.",
              grammarHintHindi: "Use simple present sentences like: I am fine.",
              lessonType: "conversation",
            },
            {
              day: 2,
              title: "How Are You",
              word: "feeling",
              meaning: "Answering how you feel",
              example: "I am good today.",
              vocabulary: ["fine", "good", "okay", "happy"],
              supportWords: ["fine", "good", "okay", "happy"],
              speakingFocus: "Talking about feelings",
              practicePrompt: "Say how you feel today.",
              grammarHintHindi: "Use 'I am feeling...' or 'I am...'",
              lessonType: "conversation",
            },
          ],
        },
        {
          week: 4,
          title: "Daily Routine",
          days: [
            {
              day: 1,
              title: "Morning Routine",
              word: "routine",
              meaning: "Daily morning activities",
              example: "I wake up early in the morning.",
              vocabulary: ["wake", "brush", "breakfast", "ready"],
              supportWords: ["wake", "brush", "breakfast", "ready"],
              speakingFocus: "Talking about morning routine",
              practicePrompt: "Describe your morning routine.",
              grammarHintHindi: "Use simple present like: I wake up.",
              lessonType: "conversation",
            },
          ],
        },
      ],
    },

    {
      level: 2,
      name: "Basic Sentence Building",
      weeks: [
        {
          week: 1,
          title: "Using I Am",
          days: [
            {
              day: 1,
              title: "I Am Sentences",
              word: "identity",
              meaning: "Talking about yourself",
              example: "I am a student.",
              vocabulary: ["student", "happy", "ready", "learning"],
              supportWords: ["student", "happy", "ready", "learning"],
              speakingFocus: "Using I am sentences",
              practicePrompt: "Say three I am sentences.",
              grammarHintHindi: "Structure: I am + adjective/noun",
              lessonType: "conversation",
            },
          ],
        },
      ],
    },

    {
      level: 5,
      name: "Interview English",
      weeks: [
        {
          week: 5,
          title: "Interview Introduction",
          days: [
            {
              day: 1,
              title: "Professional Introduction",
              word: "introduction",
              meaning: "Interview self introduction",
              example: "Good morning and thank you for this opportunity.",
              vocabulary: ["experience", "skills", "team", "responsibility"],
              supportWords: ["experience", "skills", "team", "responsibility"],
              speakingFocus: "Professional self introduction",
              practicePrompt: "Introduce yourself in interview style.",
              grammarHintHindi: "Use confident sentences.",
              lessonType: "interview",
            },
          ],
        },
      ],
    },

    {
      level: 6,
      name: "Verb Tense Speaking Lab",
      weeks: [
        {
          week: 1,
          title: "Daily Verb Practice - Week 1",
          days: [
            {
              day: 1,
              title: "Verb Practice: Write",
              word: "write",
              meaning: "likhna",
              example: "I write every day.",
              vocabulary: ["write", "writing", "written", "wrote"],
              supportWords: ["write", "writing", "written", "wrote"],
              speakingFocus: "Using the verb write in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai write. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "write",
              verbMeaning: "likhna",
              tenseLines: [
                "Main likhta hoon.",
                "Main likh raha hoon.",
                "Main likh chuka hoon.",
                "Main do ghante se likh raha hoon.",
                "Main kal likha.",
                "Main likh raha tha.",
                "Main likh chuka tha.",
                "Main do ghante se likh raha tha.",
                "Main likhunga.",
                "Main likh raha hunga.",
                "Main likh chuka hunga.",
                "Main do ghante se likh raha hunga.",
              ],
              answers: [
                "I write.",
                "I am writing.",
                "I have written.",
                "I have been writing for two hours.",
                "I wrote yesterday.",
                "I was writing.",
                "I had written.",
                "I had been writing for two hours.",
                "I will write.",
                "I will be writing.",
                "I will have written.",
                "I will have been writing for two hours.",
              ],
            },
            {
              day: 2,
              title: "Verb Practice: Read",
              word: "read",
              meaning: "padhna",
              example: "I read every day.",
              vocabulary: ["read", "reading"],
              supportWords: ["read", "reading"],
              speakingFocus: "Using the verb read in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai read. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "read",
              verbMeaning: "padhna",
              tenseLines: [
                "Main padhta hoon.",
                "Main padh raha hoon.",
                "Main padh chuka hoon.",
                "Main do ghante se padh raha hoon.",
                "Main kal padha.",
                "Main padh raha tha.",
                "Main padh chuka tha.",
                "Main do ghante se padh raha tha.",
                "Main padhunga.",
                "Main padh raha hunga.",
                "Main padh chuka hunga.",
                "Main do ghante se padh raha hunga.",
              ],
              answers: [
                "I read.",
                "I am reading.",
                "I have read.",
                "I have been reading for two hours.",
                "I read yesterday.",
                "I was reading.",
                "I had read.",
                "I had been reading for two hours.",
                "I will read.",
                "I will be reading.",
                "I will have read.",
                "I will have been reading for two hours.",
              ],
            },
            {
              day: 3,
              title: "Verb Practice: Go",
              word: "go",
              meaning: "jana",
              example: "I go to school every day.",
              vocabulary: ["go", "going", "gone", "went"],
              supportWords: ["go", "going", "gone", "went"],
              speakingFocus: "Using the verb go in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai go. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "go",
              verbMeaning: "jana",
              tenseLines: [
                "Main jaata hoon.",
                "Main ja raha hoon.",
                "Main ja chuka hoon.",
                "Main do ghante se ja raha hoon.",
                "Main kal gaya.",
                "Main ja raha tha.",
                "Main ja chuka tha.",
                "Main do ghante se ja raha tha.",
                "Main jaunga.",
                "Main ja raha hunga.",
                "Main ja chuka hunga.",
                "Main do ghante se ja raha hunga.",
              ],
              answers: [
                "I go.",
                "I am going.",
                "I have gone.",
                "I have been going for two hours.",
                "I went yesterday.",
                "I was going.",
                "I had gone.",
                "I had been going for two hours.",
                "I will go.",
                "I will be going.",
                "I will have gone.",
                "I will have been going for two hours.",
              ],
            },
            {
              day: 4,
              title: "Verb Practice: Eat",
              word: "eat",
              meaning: "khana",
              example: "I eat breakfast every day.",
              vocabulary: ["eat", "eating", "eaten", "ate"],
              supportWords: ["eat", "eating", "eaten", "ate"],
              speakingFocus: "Using the verb eat in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai eat. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "eat",
              verbMeaning: "khana",
              tenseLines: [
                "Main khaata hoon.",
                "Main kha raha hoon.",
                "Main kha chuka hoon.",
                "Main do ghante se kha raha hoon.",
                "Main kal khaya.",
                "Main kha raha tha.",
                "Main kha chuka tha.",
                "Main do ghante se kha raha tha.",
                "Main khaunga.",
                "Main kha raha hunga.",
                "Main kha chuka hunga.",
                "Main do ghante se kha raha hunga.",
              ],
              answers: [
                "I eat.",
                "I am eating.",
                "I have eaten.",
                "I have been eating for two hours.",
                "I ate yesterday.",
                "I was eating.",
                "I had eaten.",
                "I had been eating for two hours.",
                "I will eat.",
                "I will be eating.",
                "I will have eaten.",
                "I will have been eating for two hours.",
              ],
            },
            {
              day: 5,
              title: "Verb Practice: Speak",
              word: "speak",
              meaning: "bolna",
              example: "I speak English every day.",
              vocabulary: ["speak", "speaking", "spoken", "spoke"],
              supportWords: ["speak", "speaking", "spoken", "spoke"],
              speakingFocus: "Using the verb speak in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai speak. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "speak",
              verbMeaning: "bolna",
              tenseLines: [
                "Main bolta hoon.",
                "Main bol raha hoon.",
                "Main bol chuka hoon.",
                "Main do ghante se bol raha hoon.",
                "Main kal bola.",
                "Main bol raha tha.",
                "Main bol chuka tha.",
                "Main do ghante se bol raha tha.",
                "Main bolunga.",
                "Main bol raha hunga.",
                "Main bol chuka hunga.",
                "Main do ghante se bol raha hunga.",
              ],
              answers: [
                "I speak.",
                "I am speaking.",
                "I have spoken.",
                "I have been speaking for two hours.",
                "I spoke yesterday.",
                "I was speaking.",
                "I had spoken.",
                "I had been speaking for two hours.",
                "I will speak.",
                "I will be speaking.",
                "I will have spoken.",
                "I will have been speaking for two hours.",
              ],
            },
            {
              day: 6,
              title: "Verb Practice: Make",
              word: "make",
              meaning: "banana",
              example: "I make tea every day.",
              vocabulary: ["make", "making", "made"],
              supportWords: ["make", "making", "made"],
              speakingFocus: "Using the verb make in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai make. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "make",
              verbMeaning: "banana",
              tenseLines: [
                "Main banaata hoon.",
                "Main bana raha hoon.",
                "Main bana chuka hoon.",
                "Main do ghante se bana raha hoon.",
                "Main kal banaya.",
                "Main bana raha tha.",
                "Main bana chuka tha.",
                "Main do ghante se bana raha tha.",
                "Main banaunga.",
                "Main bana raha hunga.",
                "Main bana chuka hunga.",
                "Main do ghante se bana raha hunga.",
              ],
              answers: [
                "I make.",
                "I am making.",
                "I have made.",
                "I have been making for two hours.",
                "I made yesterday.",
                "I was making.",
                "I had made.",
                "I had been making for two hours.",
                "I will make.",
                "I will be making.",
                "I will have made.",
                "I will have been making for two hours.",
              ],
            },
            {
              day: 7,
              title: "Verb Practice: See",
              word: "see",
              meaning: "dekhna",
              example: "I see the teacher every day.",
              vocabulary: ["see", "seeing", "seen", "saw"],
              supportWords: ["see", "seeing", "seen", "saw"],
              speakingFocus: "Using the verb see in 12 tense patterns",
              practicePrompt: "Speak each Hinglish line in correct English.",
              grammarHintHindi:
                "Aaj ka verb hai see. Har line ko English mein bolna hai.",
              lessonType: "verb_tense",
              verb: "see",
              verbMeaning: "dekhna",
              tenseLines: [
                "Main dekhta hoon.",
                "Main dekh raha hoon.",
                "Main dekh chuka hoon.",
                "Main do ghante se dekh raha hoon.",
                "Main kal dekha.",
                "Main dekh raha tha.",
                "Main dekh chuka tha.",
                "Main do ghante se dekh raha tha.",
                "Main dekhunga.",
                "Main dekh raha hunga.",
                "Main dekh chuka hunga.",
                "Main do ghante se dekh raha hunga.",
              ],
              answers: [
                "I see.",
                "I am seeing.",
                "I have seen.",
                "I have been seeing for two hours.",
                "I saw yesterday.",
                "I was seeing.",
                "I had seen.",
                "I had been seeing for two hours.",
                "I will see.",
                "I will be seeing.",
                "I will have seen.",
                "I will have been seeing for two hours.",
              ],
            },
          ],
        },
      ],
    },
  ],
};

const PHRASE_LIBRARY = {
  "L1-W1-D1": [
    { id: 1, english: "Hello sir.", cue: "Say a greeting." },
    { id: 2, english: "Good morning.", cue: "Morning greeting." },
    { id: 3, english: "How are you?", cue: "Ask politely." },
    { id: 4, english: "I am fine.", cue: "Give a simple reply." },
    { id: 5, english: "Nice to meet you.", cue: "Finish greeting politely." },
  ],

  "L1-W4-D1": [
    { id: 1, english: "I wake up early.", cue: "Say when you wake up." },
    { id: 2, english: "I brush my teeth.", cue: "Next morning action." },
    { id: 3, english: "I take a shower.", cue: "Continue routine." },
    { id: 4, english: "I drink tea.", cue: "Say breakfast drink." },
    { id: 5, english: "I eat breakfast.", cue: "Morning food sentence." },
  ],

  "L5-W5-D1": [
    {
      id: 1,
      english: "Good morning and thank you for this opportunity.",
      cue: "Interview opening.",
    },
    {
      id: 2,
      english: "My name is Amin and I have strong safety experience.",
      cue: "Professional introduction.",
    },
    {
      id: 3,
      english: "I am hardworking and responsible.",
      cue: "Mention strengths.",
    },
    {
      id: 4,
      english: "I work well with a team.",
      cue: "Talk about teamwork.",
    },
    {
      id: 5,
      english: "Thank you for considering my application.",
      cue: "Close professionally.",
    },
  ],
};

export const MASTER_PHRASE_BANK = [
  "Hello, how are you?",
  "Good morning.",
  "Good afternoon.",
  "Good evening.",
  "Nice to meet you.",
  "I am fine today.",
  "I am learning English.",
  "I live in Abu Dhabi.",
  "I come from India.",
  "I wake up early.",
  "I drink tea.",
  "I eat breakfast.",
  "I go to work.",
  "I study English.",
  "I read books.",
  "I watch TV.",
  "I talk to my friends.",
  "I like this lesson.",
  "This is interesting.",
  "Thank you very much.",
];

export const MASTER_IDIOM_BANK = [
  ["Break the ice", "start conversation", "Let's break the ice."],
  ["Piece of cake", "very easy", "This task is a piece of cake."],
  ["Hit the nail on the head", "exactly right", "You hit the nail on the head."],
  ["Under the weather", "feeling sick", "I feel under the weather."],
  ["Once in a blue moon", "very rarely", "I visit there once in a blue moon."],
  ["Burn the midnight oil", "work late", "I burned the midnight oil."],
  ["Cost an arm and a leg", "very expensive", "This costs an arm and a leg."],
  ["Cut corners", "do cheaply", "Do not cut corners."],
  ["The ball is in your court", "your decision", "The ball is in your court."],
  ["Call it a day", "stop working", "Let's call it a day."],
];

function buildLessonKey(level, week, day) {
  return `L${level}-W${week}-D${day}`;
}

function buildDefaultPhrasesFromLesson(lesson) {
  return [
    {
      id: 1,
      english: lesson.example,
      cue: "Repeat this sentence.",
    },
  ];
}

export function getLessonWithContext(levelNumber, weekNumber, dayNumber) {
  const level = COURSE_DATA.levels.find(
    (l) => l.level === Number(levelNumber)
  );

  if (!level) return null;

  const week = level.weeks.find((w) => w.week === Number(weekNumber));
  if (!week) return null;

  const day = week.days.find((d) => d.day === Number(dayNumber));
  if (!day) return null;

  const lessonKey = buildLessonKey(level.level, week.week, day.day);

  const phrases =
    PHRASE_LIBRARY[lessonKey] || buildDefaultPhrasesFromLesson(day);

  return {
    ...day,
    phrases,
    level: level.level,
    week: week.week,
  };
}